In [1]:
import torch
import numpy as np

In [2]:
#1
#Tensors can be created directly from data. The data type is automatically inferred.
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [3]:
#2
#Tensors can be created from NumPy arrays:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [4]:
#3
#From another tensor:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [5]:
#4
tensor = torch.ones(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [6]:
#5
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [7]:
#6
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [8]:
#7
tensor = torch.ones(4, 4)
y1 = tensor @ tensor.T
y2 = tensor * tensor.T
print(y1)
print(y2)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [9]:
#8
y3 = torch.rand_like(y1)
print(y3)
agg = y3.sum()
print(agg)

tensor([[0.9101, 0.5542, 0.5942, 0.0215],
        [0.1493, 0.2214, 0.8814, 0.3105],
        [0.5179, 0.7809, 0.8031, 0.4925],
        [0.9049, 0.1583, 0.4884, 0.4462]])
tensor(8.2348)


In [10]:
#9
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [11]:
#10
# A change in the tensor reflects in the NumPy array.
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [12]:
#11
n = np.ones(5)
t = torch.from_numpy(n)
# Changes in the NumPy array reflects in the tensor.
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [13]:
#12
import os
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cpu device


In [14]:
#13
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [15]:
#14
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

Predicted class: tensor([2])


In [16]:
#15
input_image = torch.rand(3,28,28)
print(input_image.size())

torch.Size([3, 28, 28])


In [17]:
#16
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [18]:
#17
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [19]:
#18
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[ 6.4856e-02, -4.2316e-01, -8.5155e-01, -1.1756e-01, -3.2106e-02,
         -5.4321e-01, -1.0749e-01, -9.1400e-02,  1.2128e-01, -5.2399e-01,
         -2.3292e-01, -2.4832e-01, -3.0595e-02,  8.3230e-01, -6.9209e-01,
          5.0494e-01,  4.5998e-02, -9.5490e-02,  5.6728e-01,  2.3503e-01],
        [ 1.4589e-01, -2.6119e-02, -1.0344e+00, -4.9591e-02, -3.6673e-01,
         -2.1781e-01, -4.8564e-01, -2.9390e-01, -8.9469e-02, -2.5731e-01,
         -1.2807e-01, -3.3165e-02,  1.3864e-02,  9.5503e-01, -4.1700e-01,
          2.7623e-01, -1.2735e-04,  2.1558e-02,  7.3356e-01,  1.4439e-01],
        [ 1.2546e-01, -2.2675e-01, -8.8932e-01,  1.1548e-01, -1.8812e-01,
         -4.0079e-02, -7.1251e-01,  4.2186e-02, -7.9129e-02, -1.0010e-01,
         -1.2016e-01, -2.9931e-02, -1.3913e-01,  7.0165e-01, -5.2697e-01,
          4.7240e-01,  1.3789e-01,  1.0803e-01,  3.3929e-01,  1.7834e-01]],
       grad_fn=<AddmmBackward0>)


After ReLU: tensor([[0.0649, 0.0000, 0.0000, 0.0000, 0.0000,

In [20]:
#19
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3,28,28)
logits = seq_modules(input_image)

In [21]:
#20
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)

In [22]:
#21
print(f"Model structure: {model}\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Model structure: NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values : tensor([[ 0.0136, -0.0139,  0.0154,  ..., -0.0129,  0.0189, -0.0189],
        [ 0.0005, -0.0094, -0.0165,  ...,  0.0176, -0.0182, -0.0065]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) | Values : tensor([-0.0079, -0.0195], grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values : tensor([[-0.0371,  0.0168, -0.0069,  ...,  0.0342, -0.0066, -0.0224],
        [ 0.0080,  0.0067, -0.0044,  ...,  0.0119,  0.0427, -0.0094]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.bias | 